#!/bin/bash
# Script that was used to build this package. Enjoy

NAME="$1"; shift
APP="$1"; shift
EXE="$1"; shift


# wine bottle location
[ -z "$WINE" ] && WINE=~/.local/share/lutris/runners/wine/staging-2.21-i386

NICE_NAME=$(echo $(echo "$NAME" | sed 's/[A-Z]/ \0/g'))
DOT_NAME=$(echo "$NICE_NAME" | tr " " . )
WINEEXE="/app/bin/wine64"
SRCLIB="/usr/lib/"
LDLINUX=""
ARCH="x86_64"
LIB="lib64"
SRCBIN="/usr/bin"

if [[ "$WINE" == *"i386"* ]] ; then
	WINEEXE="/app/bin/wine"
	SRCLIB="/usr/lib32/"
	LDLINUX=$SRCLIB/ld-linux.so.2
	ARCH="i386"
	LIB="lib"
	SRCBIN="/usr/bin"
fi

mkdir -p target/package/files/bin
mkdir -p target/package/files/etc
mkdir -p target/package/export/share/applications
mkdir -p target/package/export/share/icons/hicolor
mkdir -p target/\[Flatpak-Riot\ Games\]$DOT_NAME

cat << EOF > target/package/files/bin/run.sh
#!/bin/bash
mkdir -p /tmp/wine.$$.prefix/
export WINEPREFIX=\$HOME/.local/share/flatpak-riotgames/$NAME/
export WINEEXE="$WINEEXE"
export WINEDEBUG="-all"
export GPU_MAX_HEAP_SIZE="100"
export GPU_MAX_ALLOC_PERCENT="100"
export MESA_GLTHREAD=true
export __GL_THREADED_OPTIMIZATIONS=1

cd "/app/$(basename "$APP")"

if ! [ -e "\$WINEPREFIX/drive_c/Riot Games" ] ; then
	winetricks -q directx9 winxp &&
	curl -L -o "\$WINEPREFIX/drive_c/LeagueInstallerNA.exe" https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20NA.exe
	$WINEEXE regedit /C $NAME.reg &&
	cp $NAME.md "\$WINEPREFIX/$NAME.md" &&
	sed -i 's/FLATPAKNAME/org.RiotGames.$NAME/g' "\$WINEPREFIX/$NAME.md" &&
	sed -i "s|WINEPREFIX|\$WINEPREFIX|" "\$WINEPREFIX/$NAME.md"
	$WINEEXE "\$WINEPREFIX/drive_c/LeagueInstallerNA.exe" \$@
	exit $?
fi

if [ "\$1" == "winecfg" ] ; then
	$WINEEXE winecfg
elif [ "\$1" == "winetricks" ] ; then
	winetricks
elif [ "\$1" == "regedit" ] ; then
	$WINEEXE regedit
elif [ "\$1" == "bash" ] ; then
	bash 
elif [ -e run.sh ] ; then
	sh run.sh \$@
	exit $?
else
	$WINEEXE "\$WINEPREFIX/drive_c/Riot Games/League of Legends/$EXE" \$@
	exit $?
fi
EOF

cat << EOF >target/package/metadata
[Application]
name=org.RiotGames.$NAME
runtime=org.freedesktop.Platform/$ARCH/1.6
sdk=org.freedesktop.Sdk/$ARCH/1.6
command=run.sh

[Context]
features=devel;multiarch;
shared=network;ipc;
sockets=x11;pulseaudio;
devices=dri;
filesystems=xdg-documents;~/.local/share/flatpak-riotgames/:create
EOF

cat << EOF >target/package/export/share/applications/org.RiotGames.$NAME.desktop
[Desktop Entry]
Version=1.0
Name=$NICE_NAME
Exec=flatpak run org.RiotGames.leagueoflegends $@
Icon=org.RiotGames.$NAME
StartupNotify=true
Terminal=false
Type=Application
Categories=Game;
EOF


set -ex
[ -e "$APP"/icon.png ] && cp "$APP"/icon.png target/package/export/share/icons/hicolor/org.RiotGames.$NAME.png

cp -rd "$APP" target/package/files/
cp -rd $WINE/bin $WINE/$LIB $WINE/share target/package/files/
cp -d $SRCBIN/winetricks target/package/files/bin/

find target/package/files/$LIB -iname "*libz*" -print -delete
[ ! -z $LDLINUX ] && cp $LDLINUX target/package/files/$LIB

# league of legends
curl -L -O http://security.ubuntu.com/ubuntu/pool/main/s/systemd/libudev1_229-4ubuntu10_$ARCH.deb
curl -L -O http://security.ubuntu.com/ubuntu/pool/main/w/wget/wget_1.17.1-1ubuntu1.3_$ARCH.deb
curl -L -O http://security.ubuntu.com/ubuntu/pool/main/p/perl/perl_5.22.1-9ubuntu0.2_$ARCH.deb
curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_$ARCH.deb
curl -L -O http://mirrors.kernel.org/ubuntu/pool/multiverse/u/unrar-nonfree/unrar_5.3.2-1_$ARCH.deb
curl -L -O http://mirrors.kernel.org/ubuntu/pool/universe/c/cabextract/cabextract_1.6-1_$ARCH.deb
curl -L -O http://mirrors.kernel.org/ubuntu/pool/universe/libp/libpsl/libpsl0_0.11.0-2_$ARCH.deb
curl -L -O http://mirrors.kernel.org/ubuntu/pool/universe/c/clisp/clisp-module-gdbm_2.49-9ubuntu1_$ARCH.deb
curl -L -O http://mirrors.kernel.org/ubuntu/pool/universe/p/p7zip/p7zip_9.20.1~dfsg.1-4.2_$ARCH.deb
curl -L -O http://mirrors.kernel.org/ubuntu/pool/main/libm/libmspack/libmspack0_0.6-3_$ARCH.deb

ar x libudev*
tar -xf data.tar.xz
ar x wget*
tar -xf data.tar.xz
ar x cabextract*
tar -xf data.tar.xz
ar x libpsl*
tar -xf data.tar.xz
ar x libpng12*
tar -xf data.tar.xz
ar x unrar*
tar -xf data.tar.xz
ar x clisp-module-gdbm*
tar -xf data.tar.xz
ar x perl*
tar -xf data.tar.xz
ar x p7zip*
tar -xf data.tar.xz
ar x libmspack*
tar -xf data.tar.xz

cp lib/$ARCH-linux-gnu/* target/package/files/lib/
cp usr/lib/$ARCH-linux-gnu/libpsl* target/package/files/lib/
cp usr/bin/* target/package/files/bin/
cp -R etc target/package/files/
cp -R usr/lib/clisp* target/package/files/lib/
cp -R usr/lib/p7zip* target/package/files/lib/

git clone https://github.com/Winetricks/winetricks.git
make -C winetricks/ DESTDIR=build install
cp winetricks/build/usr/bin/winetricks target/package/files/bin/

chmod +x target/package/files/bin/run.sh
chmod +x target/package/files/bin/winetricks
chmod +x target/package/files/bin/7zr
chmod +x target/package/files/bin/cabextract
chmod +x target/package/files/bin/p7zip
chmod +x target/package/files/bin/unrar-nonfree
chmod +x target/package/files/bin/wget
chmod +x target/package/files/bin/perldoc
chmod +x target/package/files/lib/clisp-2.49/gdbm/link.sh


flatpak build-export target/repo target/package
flatpak build-bundle --arch=$ARCH target/repo target/\[Flatpak-Riot\ Games\]$DOT_NAME/$NAME.flatpak org.RiotGames.$NAME
mv target/\[Flatpak-Riot\ Games\]$DOT_NAME/$NAME.flatpak ./

# cleanup
rm -Rf usr lib etc winetricks *.xz *.gz *.deb debian-binary target
